framework:
    messenger:
        transports:
            user_create:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: amq.direct
                        type: direct
                        default_publish_routing_key: '%routing_key.user_create%'
                    queues:
                        user_create_queue:
                            binding_keys: ['%routing_key.user_create%']

            tracking_data_create:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: amq.direct
                        type: direct
                        default_publish_routing_key: '%routing_key.tracking_data_create%'
                    queues:
                        tracking_data_create_queue:
                            binding_keys: ['%routing_key.tracking_data_create%']

        routing:
            'App\ValueObject\User': user_create
            'App\ValueObject\TrackingData': tracking_data_create
